#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_TEST_BRENDAN,
    MUGSHOT_TEST_MAY,
    MUGSHOT_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
